import { describe, it, expect } from "vitest";
import {
  INSTITUTIONS,
  institutionById,
  demoConnection,
  holdingsFromConnections,
  cashFromConnections,
  mergePositions,
  aggregateBySymbol,
  summarizeByBroker,
  normalizePlaidHoldings,
  speakableBrokerLine,
  matchInstitution,
  brokerPlanGate,
  BROKER_PLAN,
} from "./brokers.js";

describe("the catalog", () => {
  it("carries the three institutions the desk offers", () => {
    expect(INSTITUTIONS.map((i) => i.id)).toEqual(["robinhood", "schwab", "morgan-stanley"]);
  });
  it("names an institution, and does not invent one", () => {
    expect(institutionById("schwab").name).toBe("Charles Schwab");
    expect(institutionById("nope")).toBeNull();
  });
});

describe("the demo book", () => {
  it("is fixed, not random — the same call twice is the same book", () => {
    const a = demoConnection("morgan-stanley", 1000);
    const b = demoConnection("morgan-stanley", 1000);
    expect(a).toEqual(b);
  });
  it("labels itself demo on the connection", () => {
    expect(demoConnection("robinhood").demo).toBe(true);
  });
  it("refuses an institution it does not know", () => {
    expect(demoConnection("etrade")).toBeNull();
  });
  it("gives Morgan Stanley more than one account", () => {
    expect(demoConnection("morgan-stanley").accounts.length).toBeGreaterThan(1);
  });
  it("mixes winners and losers so the P&L colouring has something to do", () => {
    // Cost bases straddle the app's demo bases; the point is only that they are
    // not all on one side, which a book generated by one formula would be.
    const rows = holdingsFromConnections([demoConnection("schwab")]);
    const costs = rows.map((r) => r.cost);
    expect(new Set(costs).size).toBe(costs.length);
  });
});

describe("connections → rows", () => {
  const conns = [demoConnection("robinhood", 1), demoConnection("schwab", 1)];

  it("flattens every account of every connection", () => {
    const rows = holdingsFromConnections(conns);
    expect(rows.length).toBe(3 + 3 + 2); // rh individual + schwab brokerage + schwab roth
  });

  it("stamps provenance on each row", () => {
    const row = holdingsFromConnections(conns).find((r) => r.sym === "TSLA");
    expect(row.broker).toBe("robinhood");
    expect(row.brokerName).toBe("Robinhood");
    expect(row.account).toBe("Individual");
    expect(row.source).toBe("linked");
    expect(row.demo).toBe(true);
  });

  it("gives a row an id that survives a refetch", () => {
    const first = holdingsFromConnections([demoConnection("schwab", 1)]);
    const again = holdingsFromConnections([demoConnection("schwab", 99999)]);
    expect(first.map((r) => r.id)).toEqual(again.map((r) => r.id));
  });

  it("drops a holding with no symbol or no shares", () => {
    const rows = holdingsFromConnections([
      {
        id: "x", institutionId: "schwab", accounts: [
          { id: "a", name: "A", holdings: [{ sym: "", shares: 5 }, { sym: "AAPL", shares: 0 }, { sym: "MSFT", shares: 3, cost: 1 }] },
        ],
      },
    ]);
    expect(rows.map((r) => r.sym)).toEqual(["MSFT"]);
  });

  it("keeps cash out of the positions and in its own list", () => {
    const rows = holdingsFromConnections(conns);
    expect(rows.some((r) => r.sym === "CASH")).toBe(false);
    const cash = cashFromConnections(conns);
    expect(cash.length).toBe(3);
    expect(cash.every((c) => c.cash > 0)).toBe(true);
  });

  it("survives an empty or malformed connection list", () => {
    expect(holdingsFromConnections()).toEqual([]);
    expect(holdingsFromConnections([{ id: "a" }])).toEqual([]);
    expect(cashFromConnections([{ id: "a", accounts: [{ id: "b", cash: null }] }])).toEqual([]);
  });
});

describe("merging typed positions with linked ones", () => {
  it("puts the typed ones first and marks their source", () => {
    const merged = mergePositions(
      [{ id: "m1", sym: "AAPL", shares: 1, cost: 100 }],
      holdingsFromConnections([demoConnection("robinhood", 1)]),
    );
    expect(merged[0].source).toBe("manual");
    expect(merged[0].broker).toBeNull();
    expect(merged.slice(1).every((r) => r.source === "linked")).toBe(true);
  });

  it("does NOT fold a linked lot into a typed lot of the same symbol", () => {
    const merged = mergePositions(
      [{ id: "m1", sym: "TSLA", shares: 10, cost: 100 }],
      holdingsFromConnections([demoConnection("robinhood", 1)]),
    );
    expect(merged.filter((r) => r.sym === "TSLA").length).toBe(2);
  });
});

describe("aggregateBySymbol", () => {
  it("share-weights the cost across accounts", () => {
    const agg = aggregateBySymbol([
      { sym: "MSFT", shares: 100, cost: 300 },
      { sym: "MSFT", shares: 100, cost: 400 },
    ]);
    expect(agg).toHaveLength(1);
    expect(agg[0].shares).toBe(200);
    expect(agg[0].cost).toBe(350);
    expect(agg[0].costTotal).toBe(70000);
  });

  it("weights by shares, not by row count", () => {
    const agg = aggregateBySymbol([
      { sym: "AAPL", shares: 300, cost: 100 },
      { sym: "AAPL", shares: 100, cost: 200 },
    ]);
    expect(agg[0].cost).toBe(125);
  });

  it("lists every broker holding the symbol", () => {
    const agg = aggregateBySymbol([
      { sym: "MSFT", shares: 10, cost: 1, broker: "schwab" },
      { sym: "MSFT", shares: 10, cost: 1, broker: "morgan-stanley" },
    ]);
    expect(agg[0].brokers.sort()).toEqual(["morgan-stanley", "schwab"]);
  });

  it("does not divide by zero on a net-flat symbol", () => {
    const agg = aggregateBySymbol([
      { sym: "NVDA", shares: 10, cost: 100 },
      { sym: "NVDA", shares: -10, cost: 120 },
    ]);
    expect(agg[0].shares).toBe(0);
    expect(agg[0].cost).toBe(0);
    expect(Number.isNaN(agg[0].cost)).toBe(false);
  });
});

describe("summarizeByBroker", () => {
  const rows = [
    { sym: "AAPL", shares: 10, cost: 100, broker: "schwab", brokerName: "Charles Schwab", demo: true },
    { sym: "MSFT", shares: 10, cost: 100, broker: "schwab", brokerName: "Charles Schwab", demo: true },
    { sym: "TSLA", shares: 5, cost: 200, broker: "robinhood", brokerName: "Robinhood", demo: true },
  ];

  it("totals value and P&L per broker", () => {
    const [schwab] = summarizeByBroker(rows, (s) => (s === "AAPL" ? 150 : 90));
    expect(schwab.broker).toBe("schwab");
    expect(schwab.positions).toBe(2);
    expect(schwab.value).toBe(150 * 10 + 90 * 10);
    expect(schwab.cost).toBe(2000);
    expect(schwab.pnl).toBe(400);
    expect(schwab.pnlPct).toBeCloseTo(20, 6);
  });

  it("falls back to cost for a symbol it cannot price, and says how many it marked", () => {
    const [schwab] = summarizeByBroker(rows, (s) => (s === "AAPL" ? 150 : null));
    expect(schwab.priced).toBe(1);
    expect(schwab.value).toBe(150 * 10 + 100 * 10);
    expect(schwab.pnl).toBe(500);
  });

  it("skips typed positions, which belong to no broker", () => {
    const out = summarizeByBroker([...rows, { sym: "X", shares: 1, cost: 1, broker: null }], () => 1);
    expect(out.map((b) => b.broker).sort()).toEqual(["robinhood", "schwab"]);
  });
});

// The one adapter that talks to a real provider is also the one that cannot be
// exercised without credentials — so the join is tested against Plaid's
// documented response shape instead, which is the part that can actually be
// wrong in a way nobody notices.
describe("normalizePlaidHoldings", () => {
  const payload = {
    accounts: [
      { account_id: "acc1", name: "Plaid IRA", mask: "6666", type: "investment", subtype: "ira", balances: { available: 1500.5 } },
    ],
    securities: [
      { security_id: "sec1", ticker_symbol: "AAPL", name: "Apple Inc.", type: "equity" },
      { security_id: "cash", ticker_symbol: null, name: "US Dollar", type: "cash" },
    ],
    holdings: [
      { account_id: "acc1", security_id: "sec1", quantity: 100, cost_basis: 15000, institution_price: 200 },
      { account_id: "acc1", security_id: "cash", quantity: 1500.5, cost_basis: 1500.5, institution_price: 1 },
    ],
  };

  it("joins holdings to securities and accounts", () => {
    const conn = normalizePlaidHoldings(payload, { institutionId: "schwab", connectionId: "c1" });
    expect(conn.accounts).toHaveLength(1);
    expect(conn.accounts[0].name).toBe("Plaid IRA");
    expect(conn.accounts[0].holdings).toHaveLength(1);
    expect(conn.accounts[0].holdings[0].sym).toBe("AAPL");
  });

  it("converts Plaid's TOTAL cost basis to this app's per-share cost", () => {
    const conn = normalizePlaidHoldings(payload, { institutionId: "schwab" });
    expect(conn.accounts[0].holdings[0].cost).toBe(150);
  });

  it("drops the untickered cash row rather than drawing a nameless position", () => {
    const conn = normalizePlaidHoldings(payload, { institutionId: "schwab" });
    expect(conn.accounts[0].holdings.map((h) => h.sym)).toEqual(["AAPL"]);
  });

  it("takes cash from the account balance", () => {
    const conn = normalizePlaidHoldings(payload, { institutionId: "schwab" });
    expect(conn.accounts[0].cash).toBe(1500.5);
  });

  it("is never marked demo", () => {
    expect(normalizePlaidHoldings(payload, { institutionId: "schwab" }).demo).toBe(false);
  });

  it("treats an absurd per-share result as an already-per-share field", () => {
    // 100 shares marked at $200 cannot have cost $200,000 EACH. A provider that
    // put a per-share figure in cost_basis would otherwise be silently scaled.
    const odd = {
      ...payload,
      holdings: [{ account_id: "acc1", security_id: "sec1", quantity: 100, cost_basis: 200000000, institution_price: 200 }],
    };
    expect(normalizePlaidHoldings(odd, { institutionId: "schwab" }).accounts[0].holdings[0].cost).toBe(200000000);
  });

  it("does not divide by zero, and survives an empty payload", () => {
    const zero = { ...payload, holdings: [{ account_id: "acc1", security_id: "sec1", quantity: 0, cost_basis: 10 }] };
    expect(normalizePlaidHoldings(zero, { institutionId: "schwab" }).accounts).toEqual([]);
    expect(normalizePlaidHoldings({}, { institutionId: "schwab" }).accounts).toEqual([]);
    expect(normalizePlaidHoldings(undefined, { institutionId: "schwab" }).accounts).toEqual([]);
  });
});

describe("speakableBrokerLine", () => {
  const rows = [{ sym: "AAPL", shares: 10, cost: 100, broker: "schwab", brokerName: "Charles Schwab" }];

  it("reads a broker's book in one sentence", () => {
    const line = speakableBrokerLine("schwab", rows, () => 150, (n) => `$${n.toFixed(0)}`);
    expect(line).toBe("Charles Schwab: 1 position, up $500, 50.0 percent.");
  });

  it("says nothing about a broker with nothing in it", () => {
    expect(speakableBrokerLine("robinhood", rows, () => 150)).toBeNull();
  });
});

describe("matchInstitution", () => {
  it("hears each institution by name", () => {
    expect(matchInstitution("how's my robinhood account")).toBe("robinhood");
    expect(matchInstitution("pull up my Robin Hood positions")).toBe("robinhood");
    expect(matchInstitution("brief my schwab holdings")).toBe("schwab");
    expect(matchInstitution("what's in TD Ameritrade")).toBe("schwab");
    expect(matchInstitution("show me Morgan Stanley")).toBe("morgan-stanley");
  });

  it("leaves the tickers alone — MS and HOOD chart, they do not brief", () => {
    expect(matchInstitution("MS")).toBeNull();
    expect(matchInstitution("chart HOOD")).toBeNull();
    expect(matchInstitution("MSFT earnings")).toBeNull();
  });

  it("returns null rather than guessing", () => {
    expect(matchInstitution("how is my portfolio")).toBeNull();
    expect(matchInstitution("")).toBeNull();
  });
});

// The gate guards a stored credential for somebody's brokerage account, so
// every way of NOT being on the plan is spelled out rather than assumed to
// fall out of one comparison.
describe("brokerPlanGate", () => {
  it("lets Trading Floor through", () => {
    expect(brokerPlanGate("desk")).toBeNull();
    expect(BROKER_PLAN).toBe("desk");
  });

  it("stops every lesser plan, and says which one is needed", () => {
    for (const plan of ["free", "pro"]) {
      const gate = brokerPlanGate(plan);
      expect(gate).not.toBeNull();
      expect(gate.needsPlan).toBe("desk");
      expect(gate.error).toMatch(/Trading Floor/);
    }
  });

  it("fails closed on an absent, unknown or malformed plan", () => {
    for (const plan of [undefined, null, "", "DESK", "trading-floor", 0, {}, ["desk"]]) {
      expect(brokerPlanGate(plan)).not.toBeNull();
    }
  });

  it("tells the caller a demo book is still available, so the refusal is not a dead end", () => {
    expect(brokerPlanGate("free").error).toMatch(/demonstration book/i);
  });
});
